import { Pagination, type PaginationLink } from '@/components/pagination';
import { Badge } from '@/components/ui/badge';
import { Card, CardContent } from '@/components/ui/card';
import AppLayout from '@/layouts/app-layout';
import { Head, router } from '@inertiajs/react';

interface Activity { id: number; action: string; description: string; before: Record<string, unknown> | null; after: Record<string, unknown> | null; created_at: string; user: { name: string; email: string } | null; claim: { external_id: string; patient_name: string } | null }
interface ActivityPage { data: Activity[]; links: PaginationLink[] }

export default function ActivityLogs({ activities, filters, actions, users }: { activities: ActivityPage; filters: Record<string, string>; actions: string[]; users: { id: number; name: string }[] }) {
    const apply = (field: string, value: string) => router.get('/activity-logs', { ...filters, [field]: value || undefined }, { preserveState: true, replace: true });
    return <AppLayout breadcrumbs={[{ title: 'Activity Logs', href: '/activity-logs' }]}><Head title="Activity Logs" /><div className="flex flex-1 flex-col gap-5 p-4 md:p-6"><div><h1 className="text-3xl font-semibold tracking-tight">Activity logs</h1><p className="text-sm text-muted-foreground">A trace of imports, claim changes, assignments, and access updates.</p></div><Card><CardContent className="flex flex-wrap gap-3 p-4"><select className="h-10 rounded-md border bg-background px-3 text-sm" defaultValue={filters.action ?? ''} onChange={(e) => apply('action', e.target.value)}><option value="">All actions</option>{actions.map((action) => <option key={action}>{action}</option>)}</select><select className="h-10 rounded-md border bg-background px-3 text-sm" defaultValue={filters.user_id ?? ''} onChange={(e) => apply('user_id', e.target.value)}><option value="">All users</option>{users.map((user) => <option key={user.id} value={user.id}>{user.name}</option>)}</select></CardContent></Card><Card><CardContent className="p-0"><div className="divide-y">{activities.data.length === 0 ? <p className="p-12 text-center text-muted-foreground">No activity recorded yet.</p> : activities.data.map((activity) => <div className="grid gap-3 p-4 md:grid-cols-[170px_1fr_auto] md:items-center" key={activity.id}><div><p className="text-sm font-medium">{activity.user?.name ?? 'System'}</p><p className="text-xs text-muted-foreground">{new Date(activity.created_at).toLocaleString()}</p></div><div><p className="text-sm">{activity.description}</p>{activity.claim && <p className="text-xs text-muted-foreground">{activity.claim.external_id} · {activity.claim.patient_name}</p>}</div><Badge variant="outline">{activity.action.replaceAll('_', ' ')}</Badge></div>)}</div><div className="border-t p-4"><Pagination links={activities.links} /></div></CardContent></Card></div></AppLayout>;
}
